platform :ios, '12.0'

project 'Runner.xcworkspace'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Add any other pods you need
  
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable bitcode and exclude arm64 architecture for the simulator
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
      # Ensure all modules are correctly linked
      config.build_settings['DEFINES_MODULE'] = 'YES'
    end
  end
end
